// Package famly is bairn's typed client for the Famly vendor surface.
//
// The package combines two transports:
//
//   - GraphQL operations generated by genqlient (gen.go), validated
//     against the SDL in schema.graphql at codegen time.
//   - Hand-written REST methods for endpoints that don't have
//     useful GraphQL equivalents (or where the REST shape is
//     simpler).
//
// Client is concurrency-safe for parallel requests against the same
// session token.
package famly

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// DefaultBaseURL is the production Famly endpoint. Override per-Client
// for fixture servers in tests.
const DefaultBaseURL = "https://app.famly.co"

// DefaultUserAgent identifies bairn to Famly. Polite single-account
// usage; not impersonating an official client.
const DefaultUserAgent = "bairn/0.1 (+https://gitlab.com/dunn.dev/bairn)"

// authHeader is the header Famly's v2 surface expects for session
// auth. The v1 surface accepts the same header even though the
// official client historically used a query-string variant.
const authHeader = "x-famly-accesstoken"

// ErrUnauthorized is returned when Famly responds 401. Callers that
// hold refresh credentials should attempt a token refresh and retry
// once. Callers that only have a static token should surface the
// error to the operator with refresh instructions.
var ErrUnauthorized = errors.New("famly: unauthorized")

// Client is a session-authenticated Famly client.
type Client struct {
	baseURL    string
	userAgent  string
	httpClient *http.Client
	logger     *slog.Logger

	tokenSrc TokenSource
}

// Option configures a Client.
type Option func(*Client)

// WithBaseURL overrides the production endpoint. Used by tests.
func WithBaseURL(u string) Option { return func(c *Client) { c.baseURL = u } }

// WithUserAgent overrides the default User-Agent header.
func WithUserAgent(ua string) Option { return func(c *Client) { c.userAgent = ua } }

// WithHTTPClient overrides the default *http.Client.
func WithHTTPClient(h *http.Client) Option { return func(c *Client) { c.httpClient = h } }

// WithLogger sets the structured logger. Defaults to slog.Default().
func WithLogger(l *slog.Logger) Option { return func(c *Client) { c.logger = l } }

// New constructs a Client with a TokenSource and optional overrides.
func New(src TokenSource, opts ...Option) *Client {
	c := &Client{
		baseURL:    DefaultBaseURL,
		userAgent:  DefaultUserAgent,
		httpClient: &http.Client{Timeout: 30 * time.Second},
		logger:     slog.Default(),
		tokenSrc:   src,
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// do issues a request, attaches auth + UA, decodes JSON into out.
// Returns ErrUnauthorized on 401 so callers can drive refresh.
func (c *Client) do(ctx context.Context, method, path string, query url.Values, body any, out any) error {
	full := c.baseURL + path
	if len(query) > 0 {
		full += "?" + query.Encode()
	}

	var reqBody io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("famly: marshal request: %w", err)
		}
		reqBody = bytes.NewReader(buf)
	}

	req, err := http.NewRequestWithContext(ctx, method, full, reqBody)
	if err != nil {
		return fmt.Errorf("famly: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", c.userAgent)

	tok, err := c.tokenSrc.Token(ctx)
	if err != nil {
		return fmt.Errorf("famly: get token: %w", err)
	}
	req.Header.Set(authHeader, tok)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("famly: %s %s: %w", method, path, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized {
		return ErrUnauthorized
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		buf, _ := io.ReadAll(io.LimitReader(resp.Body, 1024))
		return fmt.Errorf("famly: %s %s: HTTP %d: %s", method, path, resp.StatusCode, strings.TrimSpace(string(buf)))
	}

	if out == nil {
		return nil
	}
	dec := json.NewDecoder(resp.Body)
	if err := dec.Decode(out); err != nil {
		return fmt.Errorf("famly: decode %s: %w", path, err)
	}
	return nil
}
