// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package famly

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// AuthenticateMeMeMutation includes the requested fields of the GraphQL type MeMutation.
type AuthenticateMeMeMutation struct {
	AuthenticateWithPassword AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult `json:"-"`
}

// GetAuthenticateWithPassword returns AuthenticateMeMeMutation.AuthenticateWithPassword, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutation) GetAuthenticateWithPassword() AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult {
	return v.AuthenticateWithPassword
}

func (v *AuthenticateMeMeMutation) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*AuthenticateMeMeMutation
		AuthenticateWithPassword json.RawMessage `json:"authenticateWithPassword"`
		graphql.NoUnmarshalJSON
	}
	firstPass.AuthenticateMeMeMutation = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.AuthenticateWithPassword
		src := firstPass.AuthenticateWithPassword
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal AuthenticateMeMeMutation.AuthenticateWithPassword: %w", err)
			}
		}
	}
	return nil
}

type __premarshalAuthenticateMeMeMutation struct {
	AuthenticateWithPassword json.RawMessage `json:"authenticateWithPassword"`
}

func (v *AuthenticateMeMeMutation) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *AuthenticateMeMeMutation) __premarshalJSON() (*__premarshalAuthenticateMeMeMutation, error) {
	var retval __premarshalAuthenticateMeMeMutation

	{

		dst := &retval.AuthenticateWithPassword
		src := v.AuthenticateWithPassword
		var err error
		*dst, err = __marshalAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal AuthenticateMeMeMutation.AuthenticateWithPassword: %w", err)
		}
	}
	return &retval, nil
}

// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult includes the requested fields of the GraphQL interface AuthenticateWithPasswordResult.
//
// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult is implemented by the following types:
// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged
// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed
// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded
type AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult interface {
	implementsGraphQLInterfaceAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged) implementsGraphQLInterfaceAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult() {
}
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed) implementsGraphQLInterfaceAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult() {
}
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded) implementsGraphQLInterfaceAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult() {
}

func __unmarshalAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult(b []byte, v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "AuthenticationChallenged":
		*v = new(AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged)
		return json.Unmarshal(b, *v)
	case "AuthenticationFailed":
		*v = new(AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed)
		return json.Unmarshal(b, *v)
	case "AuthenticationSucceeded":
		*v = new(AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing AuthenticateWithPasswordResult.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult: "%v"`, tn.TypeName)
	}
}

func __marshalAuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult(v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged:
		typename = "AuthenticationChallenged"

		result := struct {
			TypeName string `json:"__typename"`
			*AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged
		}{typename, v}
		return json.Marshal(result)
	case *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed:
		typename = "AuthenticationFailed"

		result := struct {
			TypeName string `json:"__typename"`
			*AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed
		}{typename, v}
		return json.Marshal(result)
	case *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded:
		typename = "AuthenticationSucceeded"

		result := struct {
			TypeName string `json:"__typename"`
			*AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticateWithPasswordResult: "%T"`, v)
	}
}

// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged includes the requested fields of the GraphQL type AuthenticationChallenged.
type AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged struct {
	Typename string               `json:"__typename"`
	Status   AuthenticationStatus `json:"status"`
}

// GetTypename returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged.Typename, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged) GetTypename() string {
	return v.Typename
}

// GetStatus returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged.Status, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationChallenged) GetStatus() AuthenticationStatus {
	return v.Status
}

// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed includes the requested fields of the GraphQL type AuthenticationFailed.
type AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed struct {
	Typename     string               `json:"__typename"`
	Status       AuthenticationStatus `json:"status"`
	ErrorTitle   string               `json:"errorTitle"`
	ErrorDetails string               `json:"errorDetails"`
}

// GetTypename returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed.Typename, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed) GetTypename() string {
	return v.Typename
}

// GetStatus returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed.Status, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed) GetStatus() AuthenticationStatus {
	return v.Status
}

// GetErrorTitle returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed.ErrorTitle, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed) GetErrorTitle() string {
	return v.ErrorTitle
}

// GetErrorDetails returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed.ErrorDetails, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationFailed) GetErrorDetails() string {
	return v.ErrorDetails
}

// AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded includes the requested fields of the GraphQL type AuthenticationSucceeded.
type AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded struct {
	Typename    string               `json:"__typename"`
	Status      AuthenticationStatus `json:"status"`
	AccessToken string               `json:"accessToken"`
	DeviceId    string               `json:"deviceId"`
}

// GetTypename returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded.Typename, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded) GetTypename() string {
	return v.Typename
}

// GetStatus returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded.Status, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded) GetStatus() AuthenticationStatus {
	return v.Status
}

// GetAccessToken returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded.AccessToken, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded) GetAccessToken() string {
	return v.AccessToken
}

// GetDeviceId returns AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded.DeviceId, and is useful for accessing the field via an interface.
func (v *AuthenticateMeMeMutationAuthenticateWithPasswordAuthenticationSucceeded) GetDeviceId() string {
	return v.DeviceId
}

// AuthenticateResponse is returned by Authenticate on success.
type AuthenticateResponse struct {
	Me *AuthenticateMeMeMutation `json:"me"`
}

// GetMe returns AuthenticateResponse.Me, and is useful for accessing the field via an interface.
func (v *AuthenticateResponse) GetMe() *AuthenticateMeMeMutation { return v.Me }

type AuthenticationStatus string

const (
	AuthenticationStatusUnknownresult                      AuthenticationStatus = "UnknownResult"
	AuthenticationStatusSucceeded                          AuthenticationStatus = "Succeeded"
	AuthenticationStatusFailedloginnotfound                AuthenticationStatus = "FailedLoginNotFound"
	AuthenticationStatusFailedinvalidpassword              AuthenticationStatus = "FailedInvalidPassword"
	AuthenticationStatusFailed                             AuthenticationStatus = "Failed"
	AuthenticationStatusFailednovalidloginsbeforepin       AuthenticationStatus = "FailedNoValidLoginsBeforePin"
	AuthenticationStatusFailednopin                        AuthenticationStatus = "FailedNoPin"
	AuthenticationStatusFailedinvalidpin                   AuthenticationStatus = "FailedInvalidPin"
	AuthenticationStatusFailedtoomanyattempts              AuthenticationStatus = "FailedTooManyAttempts"
	AuthenticationStatusFailedpasswordnotset               AuthenticationStatus = "FailedPasswordNotSet"
	AuthenticationStatusFailedhmacexpired                  AuthenticationStatus = "FailedHmacExpired"
	AuthenticationStatusFailedinvalidtwofactorcode         AuthenticationStatus = "FailedInvalidTwofactorCode"
	AuthenticationStatusFailedtoomanypinattempts           AuthenticationStatus = "FailedTooManyPinAttempts"
	AuthenticationStatusFailedoidc                         AuthenticationStatus = "FailedOIDC"
	AuthenticationStatusFailedpasswordattemptinsteadofoidc AuthenticationStatus = "FailedPasswordAttemptInsteadOfOIDC"
	AuthenticationStatusFailedinvalidrecoverycode          AuthenticationStatus = "FailedInvalidRecoveryCode"
	AuthenticationStatusFailedmultifactorsetuprequired     AuthenticationStatus = "FailedMultiFactorSetupRequired"
)

var AllAuthenticationStatus = []AuthenticationStatus{
	AuthenticationStatusUnknownresult,
	AuthenticationStatusSucceeded,
	AuthenticationStatusFailedloginnotfound,
	AuthenticationStatusFailedinvalidpassword,
	AuthenticationStatusFailed,
	AuthenticationStatusFailednovalidloginsbeforepin,
	AuthenticationStatusFailednopin,
	AuthenticationStatusFailedinvalidpin,
	AuthenticationStatusFailedtoomanyattempts,
	AuthenticationStatusFailedpasswordnotset,
	AuthenticationStatusFailedhmacexpired,
	AuthenticationStatusFailedinvalidtwofactorcode,
	AuthenticationStatusFailedtoomanypinattempts,
	AuthenticationStatusFailedoidc,
	AuthenticationStatusFailedpasswordattemptinsteadofoidc,
	AuthenticationStatusFailedinvalidrecoverycode,
	AuthenticationStatusFailedmultifactorsetuprequired,
}

// ProbeHelloHelloPayload includes the requested fields of the GraphQL type HelloPayload.
type ProbeHelloHelloPayload struct {
	Message string `json:"message"`
}

// GetMessage returns ProbeHelloHelloPayload.Message, and is useful for accessing the field via an interface.
func (v *ProbeHelloHelloPayload) GetMessage() string { return v.Message }

// ProbeResponse is returned by Probe on success.
type ProbeResponse struct {
	Hello *ProbeHelloHelloPayload `json:"hello"`
}

// GetHello returns ProbeResponse.Hello, and is useful for accessing the field via an interface.
func (v *ProbeResponse) GetHello() *ProbeHelloHelloPayload { return v.Hello }

// __AuthenticateInput is used internally by genqlient
type __AuthenticateInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	DeviceId string `json:"deviceId"`
	Legacy   bool   `json:"legacy"`
}

// GetEmail returns __AuthenticateInput.Email, and is useful for accessing the field via an interface.
func (v *__AuthenticateInput) GetEmail() string { return v.Email }

// GetPassword returns __AuthenticateInput.Password, and is useful for accessing the field via an interface.
func (v *__AuthenticateInput) GetPassword() string { return v.Password }

// GetDeviceId returns __AuthenticateInput.DeviceId, and is useful for accessing the field via an interface.
func (v *__AuthenticateInput) GetDeviceId() string { return v.DeviceId }

// GetLegacy returns __AuthenticateInput.Legacy, and is useful for accessing the field via an interface.
func (v *__AuthenticateInput) GetLegacy() bool { return v.Legacy }

// The mutation executed by Authenticate.
const Authenticate_Operation = `
mutation Authenticate ($email: EmailAddress!, $password: Password!, $deviceId: DeviceId!, $legacy: Boolean!) {
	me {
		authenticateWithPassword(email: $email, password: $password, deviceId: $deviceId, legacy: $legacy) {
			__typename
			... on AuthenticationSucceeded {
				status
				accessToken
				deviceId
			}
			... on AuthenticationFailed {
				status
				errorTitle
				errorDetails
			}
			... on AuthenticationChallenged {
				status
			}
		}
	}
}
`

// Authenticate exchanges email + password for an access token.
// Used by the refresh path in auth.go when a session token is
// rejected and refresh credentials are available.
//
// The result is a union; on Succeeded we extract accessToken. On
// Failed we surface the AuthenticationStatus and errorTitle to the
// operator with refresh guidance. Challenged (MFA, etc.) is
// treated as an unknown failure for now.
func Authenticate(
	ctx_ context.Context,
	client_ graphql.Client,
	email string,
	password string,
	deviceId string,
	legacy bool,
) (data_ *AuthenticateResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Authenticate",
		Query:  Authenticate_Operation,
		Variables: &__AuthenticateInput{
			Email:    email,
			Password: password,
			DeviceId: deviceId,
			Legacy:   legacy,
		},
	}

	data_ = &AuthenticateResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Probe.
const Probe_Operation = `
query Probe {
	hello {
		message
	}
}
`

// Probe is the placeholder operation that keeps genqlient producing
// a non-empty client. Removed once Probe is no longer the only
// read-side operation.
func Probe(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ProbeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Probe",
		Query:  Probe_Operation,
	}

	data_ = &ProbeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
