// Package imapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package imapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Api_keyScopes apiKeyContextKey = "api_key.Scopes"
	BearerScopes  bearerContextKey = "bearer.Scopes"
	CookieScopes  cookieContextKey = "cookie.Scopes"
)

// Defines values for AssetMediaStatus.
const (
	AssetMediaStatusCreated   AssetMediaStatus = "created"
	AssetMediaStatusDuplicate AssetMediaStatus = "duplicate"
)

// Valid indicates whether the value is a known member of the AssetMediaStatus enum.
func (e AssetMediaStatus) Valid() bool {
	switch e {
	case AssetMediaStatusCreated:
		return true
	case AssetMediaStatusDuplicate:
		return true
	default:
		return false
	}
}

// Defines values for AssetRejectReason.
const (
	AssetRejectReasonDuplicate         AssetRejectReason = "duplicate"
	AssetRejectReasonUnsupportedFormat AssetRejectReason = "unsupported-format"
)

// Valid indicates whether the value is a known member of the AssetRejectReason enum.
func (e AssetRejectReason) Valid() bool {
	switch e {
	case AssetRejectReasonDuplicate:
		return true
	case AssetRejectReasonUnsupportedFormat:
		return true
	default:
		return false
	}
}

// Defines values for AssetTypeEnum.
const (
	AUDIO AssetTypeEnum = "AUDIO"
	IMAGE AssetTypeEnum = "IMAGE"
	OTHER AssetTypeEnum = "OTHER"
	VIDEO AssetTypeEnum = "VIDEO"
)

// Valid indicates whether the value is a known member of the AssetTypeEnum enum.
func (e AssetTypeEnum) Valid() bool {
	switch e {
	case AUDIO:
		return true
	case IMAGE:
		return true
	case OTHER:
		return true
	case VIDEO:
		return true
	default:
		return false
	}
}

// Defines values for AssetUploadAction.
const (
	Accept AssetUploadAction = "accept"
	Reject AssetUploadAction = "reject"
)

// Valid indicates whether the value is a known member of the AssetUploadAction enum.
func (e AssetUploadAction) Valid() bool {
	switch e {
	case Accept:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for AssetVisibility.
const (
	Archive  AssetVisibility = "archive"
	Hidden   AssetVisibility = "hidden"
	Locked   AssetVisibility = "locked"
	Timeline AssetVisibility = "timeline"
)

// Valid indicates whether the value is a known member of the AssetVisibility enum.
func (e AssetVisibility) Valid() bool {
	switch e {
	case Archive:
		return true
	case Hidden:
		return true
	case Locked:
		return true
	case Timeline:
		return true
	default:
		return false
	}
}

// Defines values for PluginJsonSchemaType.
const (
	Array   PluginJsonSchemaType = "array"
	Boolean PluginJsonSchemaType = "boolean"
	Integer PluginJsonSchemaType = "integer"
	Null    PluginJsonSchemaType = "null"
	Number  PluginJsonSchemaType = "number"
	Object  PluginJsonSchemaType = "object"
	String  PluginJsonSchemaType = "string"
)

// Valid indicates whether the value is a known member of the PluginJsonSchemaType enum.
func (e PluginJsonSchemaType) Valid() bool {
	switch e {
	case Array:
		return true
	case Boolean:
		return true
	case Integer:
		return true
	case Null:
		return true
	case Number:
		return true
	case Object:
		return true
	case String:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	Exif            SourceType = "exif"
	MachineLearning SourceType = "machine-learning"
	Manual          SourceType = "manual"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case Exif:
		return true
	case MachineLearning:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for UserAvatarColor.
const (
	Amber   UserAvatarColor = "amber"
	Blue    UserAvatarColor = "blue"
	Gray    UserAvatarColor = "gray"
	Green   UserAvatarColor = "green"
	Orange  UserAvatarColor = "orange"
	Pink    UserAvatarColor = "pink"
	Primary UserAvatarColor = "primary"
	Purple  UserAvatarColor = "purple"
	Red     UserAvatarColor = "red"
	Yellow  UserAvatarColor = "yellow"
)

// Valid indicates whether the value is a known member of the UserAvatarColor enum.
func (e UserAvatarColor) Valid() bool {
	switch e {
	case Amber:
		return true
	case Blue:
		return true
	case Gray:
		return true
	case Green:
		return true
	case Orange:
		return true
	case Pink:
		return true
	case Primary:
		return true
	case Purple:
		return true
	case Red:
		return true
	case Yellow:
		return true
	default:
		return false
	}
}

// AssetBulkUploadCheckDto defines model for AssetBulkUploadCheckDto.
type AssetBulkUploadCheckDto struct {
	// Assets Assets to check
	Assets []AssetBulkUploadCheckItem `json:"assets"`
}

// AssetBulkUploadCheckItem defines model for AssetBulkUploadCheckItem.
type AssetBulkUploadCheckItem struct {
	// Checksum Base64 or hex encoded SHA1 hash
	Checksum string `json:"checksum"`

	// Id Asset ID
	Id string `json:"id"`
}

// AssetBulkUploadCheckResponseDto defines model for AssetBulkUploadCheckResponseDto.
type AssetBulkUploadCheckResponseDto struct {
	// Results Upload check results
	Results []AssetBulkUploadCheckResult `json:"results"`
}

// AssetBulkUploadCheckResult defines model for AssetBulkUploadCheckResult.
type AssetBulkUploadCheckResult struct {
	// Action Upload action
	Action AssetUploadAction `json:"action"`

	// AssetId Existing asset ID if duplicate
	AssetId *string `json:"assetId,omitempty"`

	// Id Asset ID
	Id string `json:"id"`

	// IsTrashed Whether existing asset is trashed
	IsTrashed *bool `json:"isTrashed,omitempty"`

	// Reason Rejection reason if rejected
	Reason *AssetRejectReason `json:"reason,omitempty"`
}

// AssetFaceWithoutPersonResponseDto Asset face without person
type AssetFaceWithoutPersonResponseDto struct {
	// BoundingBoxX1 Bounding box X1 coordinate
	BoundingBoxX1 int `json:"boundingBoxX1"`

	// BoundingBoxX2 Bounding box X2 coordinate
	BoundingBoxX2 int `json:"boundingBoxX2"`

	// BoundingBoxY1 Bounding box Y1 coordinate
	BoundingBoxY1 int `json:"boundingBoxY1"`

	// BoundingBoxY2 Bounding box Y2 coordinate
	BoundingBoxY2 int `json:"boundingBoxY2"`

	// Id Face ID
	Id openapi_types.UUID `json:"id"`

	// ImageHeight Image height in pixels
	ImageHeight int `json:"imageHeight"`

	// ImageWidth Image width in pixels
	ImageWidth int `json:"imageWidth"`

	// SourceType Face detection source type
	SourceType *SourceType `json:"sourceType,omitempty"`
}

// AssetMediaCreateDto defines model for AssetMediaCreateDto.
type AssetMediaCreateDto struct {
	// AssetData Asset file data
	AssetData openapi_types.File `json:"assetData"`

	// Duration Duration in milliseconds (for videos)
	Duration *int `json:"duration,omitempty"`

	// FileCreatedAt File creation date
	FileCreatedAt time.Time `json:"fileCreatedAt"`

	// FileModifiedAt File modification date
	FileModifiedAt time.Time `json:"fileModifiedAt"`

	// Filename Filename
	Filename *string `json:"filename,omitempty"`

	// IsFavorite Mark as favorite
	IsFavorite *bool `json:"isFavorite,omitempty"`

	// LivePhotoVideoId Live photo video ID
	LivePhotoVideoId *openapi_types.UUID `json:"livePhotoVideoId,omitempty"`

	// Metadata Asset metadata items
	Metadata *[]AssetMetadataUpsertItemDto `json:"metadata,omitempty"`

	// SidecarData Sidecar file data
	SidecarData *openapi_types.File `json:"sidecarData,omitempty"`

	// Visibility Asset visibility
	Visibility *AssetVisibility `json:"visibility,omitempty"`
}

// AssetMediaResponseDto defines model for AssetMediaResponseDto.
type AssetMediaResponseDto struct {
	// Id Asset media ID
	Id string `json:"id"`

	// Status Upload status
	Status AssetMediaStatus `json:"status"`
}

// AssetMediaStatus Upload status
type AssetMediaStatus string

// AssetMetadataUpsertItemDto defines model for AssetMetadataUpsertItemDto.
type AssetMetadataUpsertItemDto struct {
	// Key Metadata key
	Key string `json:"key"`

	// Value Metadata value (object)
	Value map[string]interface{} `json:"value"`
}

// AssetRejectReason Rejection reason if rejected
type AssetRejectReason string

// AssetResponseDto defines model for AssetResponseDto.
type AssetResponseDto struct {
	// Checksum Base64 encoded SHA1 hash
	Checksum string `json:"checksum"`

	// CreatedAt The UTC timestamp when the asset was originally uploaded to Immich.
	CreatedAt time.Time `json:"createdAt"`

	// DuplicateId Duplicate group ID
	DuplicateId *string `json:"duplicateId,omitempty"`

	// Duration Video/gif duration in milliseconds (null for static images)
	Duration *int `json:"duration"`

	// ExifInfo EXIF response
	ExifInfo *ExifResponseDto `json:"exifInfo,omitempty"`

	// FileCreatedAt The actual UTC timestamp when the file was created/captured, preserving timezone information. This is the authoritative timestamp for chronological sorting within timeline groups. Combined with timezone data, this can be used to determine the exact moment the photo was taken.
	FileCreatedAt time.Time `json:"fileCreatedAt"`

	// FileModifiedAt The UTC timestamp when the file was last modified on the filesystem. This reflects the last time the physical file was changed, which may be different from when the photo was originally taken.
	FileModifiedAt time.Time `json:"fileModifiedAt"`

	// HasMetadata Whether asset has metadata
	HasMetadata bool `json:"hasMetadata"`

	// Height Asset height
	Height *int `json:"height"`

	// Id Asset ID
	Id string `json:"id"`

	// IsArchived Is archived
	IsArchived bool `json:"isArchived"`

	// IsEdited Is edited
	IsEdited bool `json:"isEdited"`

	// IsFavorite Is favorite
	IsFavorite bool `json:"isFavorite"`

	// IsOffline Is offline
	IsOffline bool `json:"isOffline"`

	// IsTrashed Is trashed
	IsTrashed bool `json:"isTrashed"`

	// LibraryId Library ID
	LibraryId *openapi_types.UUID `json:"libraryId,omitempty"`

	// LivePhotoVideoId Live photo video ID
	LivePhotoVideoId *string `json:"livePhotoVideoId,omitempty"`

	// LocalDateTime The local date and time when the photo/video was taken, derived from EXIF metadata. This represents the photographer's local time regardless of timezone, stored as a timezone-agnostic timestamp. Used for timeline grouping by "local" days and months.
	LocalDateTime time.Time `json:"localDateTime"`

	// OriginalFileName Original file name
	OriginalFileName string `json:"originalFileName"`

	// OriginalMimeType Original MIME type
	OriginalMimeType *string `json:"originalMimeType,omitempty"`

	// OriginalPath Original file path
	OriginalPath string           `json:"originalPath"`
	Owner        *UserResponseDto `json:"owner,omitempty"`

	// OwnerId Owner user ID
	OwnerId string                        `json:"ownerId"`
	People  *[]PersonWithFacesResponseDto `json:"people,omitempty"`

	// Resized Is resized
	Resized *bool                  `json:"resized,omitempty"`
	Stack   *AssetStackResponseDto `json:"stack,omitempty"`
	Tags    *[]TagResponseDto      `json:"tags,omitempty"`

	// Thumbhash Thumbhash for thumbnail generation (base64) also used as the c query param for thumbnail cache busting.
	Thumbhash *string `json:"thumbhash"`

	// Type Asset type
	Type            AssetTypeEnum                        `json:"type"`
	UnassignedFaces *[]AssetFaceWithoutPersonResponseDto `json:"unassignedFaces,omitempty"`

	// UpdatedAt The UTC timestamp when the asset record was last updated in the database. This is automatically maintained by the database and reflects when any field in the asset was last modified.
	UpdatedAt time.Time `json:"updatedAt"`

	// Visibility Asset visibility
	Visibility AssetVisibility `json:"visibility"`

	// Width Asset width
	Width *int `json:"width"`
}

// AssetStackResponseDto defines model for AssetStackResponseDto.
type AssetStackResponseDto struct {
	// AssetCount Number of assets in stack
	AssetCount int `json:"assetCount"`

	// Id Stack ID
	Id string `json:"id"`

	// PrimaryAssetId Primary asset ID
	PrimaryAssetId string `json:"primaryAssetId"`
}

// AssetTypeEnum Asset type
type AssetTypeEnum string

// AssetUploadAction Upload action
type AssetUploadAction string

// AssetVisibility Asset visibility
type AssetVisibility string

// ExifResponseDto EXIF response
type ExifResponseDto struct {
	// City City name
	City *string `json:"city,omitempty"`

	// Country Country name
	Country *string `json:"country,omitempty"`

	// DateTimeOriginal Original date/time
	DateTimeOriginal *time.Time `json:"dateTimeOriginal,omitempty"`

	// Description Image description
	Description *string `json:"description,omitempty"`

	// ExifImageHeight Image height in pixels
	ExifImageHeight *int `json:"exifImageHeight,omitempty"`

	// ExifImageWidth Image width in pixels
	ExifImageWidth *int `json:"exifImageWidth,omitempty"`

	// ExposureTime Exposure time
	ExposureTime *string `json:"exposureTime,omitempty"`

	// FNumber F-number (aperture)
	FNumber *float32 `json:"fNumber,omitempty"`

	// FileSizeInByte File size in bytes
	FileSizeInByte *int `json:"fileSizeInByte,omitempty"`

	// FocalLength Focal length in mm
	FocalLength *float32 `json:"focalLength,omitempty"`

	// Iso ISO sensitivity
	Iso *int `json:"iso,omitempty"`

	// Latitude GPS latitude
	Latitude *float32 `json:"latitude,omitempty"`

	// LensModel Lens model
	LensModel *string `json:"lensModel,omitempty"`

	// Longitude GPS longitude
	Longitude *float32 `json:"longitude,omitempty"`

	// Make Camera make
	Make *string `json:"make,omitempty"`

	// Model Camera model
	Model *string `json:"model,omitempty"`

	// ModifyDate Modification date/time
	ModifyDate *time.Time `json:"modifyDate,omitempty"`

	// Orientation Image orientation
	Orientation *string `json:"orientation,omitempty"`

	// ProjectionType Projection type
	ProjectionType *string `json:"projectionType,omitempty"`

	// Rating Rating
	Rating *int `json:"rating,omitempty"`

	// State State/province name
	State *string `json:"state,omitempty"`

	// TimeZone Time zone
	TimeZone *string `json:"timeZone,omitempty"`
}

// PersonWithFacesResponseDto defines model for PersonWithFacesResponseDto.
type PersonWithFacesResponseDto struct {
	// BirthDate Person date of birth
	BirthDate *openapi_types.Date `json:"birthDate"`

	// Color Person color (hex)
	Color *string                             `json:"color,omitempty"`
	Faces []AssetFaceWithoutPersonResponseDto `json:"faces"`

	// Id Person ID
	Id string `json:"id"`

	// IsFavorite Is favorite
	IsFavorite *bool `json:"isFavorite,omitempty"`

	// IsHidden Is hidden
	IsHidden bool `json:"isHidden"`

	// Name Person name
	Name string `json:"name"`

	// ThumbnailPath Thumbnail path
	ThumbnailPath string `json:"thumbnailPath"`

	// UpdatedAt Last update date
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// PluginJsonSchemaProperty defines model for PluginJsonSchemaProperty.
type PluginJsonSchemaProperty struct {
	AdditionalProperties *PluginJsonSchemaProperty_AdditionalProperties `json:"additionalProperties,omitempty"`
	Default              interface{}                                    `json:"default,omitempty"`
	Description          *string                                        `json:"description,omitempty"`
	Enum                 *[]string                                      `json:"enum,omitempty"`
	Items                *PluginJsonSchemaProperty                      `json:"items,omitempty"`
	Properties           *map[string]PluginJsonSchemaProperty           `json:"properties,omitempty"`
	Required             *[]string                                      `json:"required,omitempty"`
	Type                 *PluginJsonSchemaType                          `json:"type,omitempty"`
}

// PluginJsonSchemaPropertyAdditionalProperties0 defines model for .
type PluginJsonSchemaPropertyAdditionalProperties0 = bool

// PluginJsonSchemaProperty_AdditionalProperties defines model for PluginJsonSchemaProperty.AdditionalProperties.
type PluginJsonSchemaProperty_AdditionalProperties struct {
	union json.RawMessage
}

// PluginJsonSchemaType defines model for PluginJsonSchemaType.
type PluginJsonSchemaType string

// ServerPingResponse defines model for ServerPingResponse.
type ServerPingResponse struct {
	Res string `json:"res"`
}

// ServerVersionResponseDto defines model for ServerVersionResponseDto.
type ServerVersionResponseDto struct {
	// Major Major version number
	Major int `json:"major"`

	// Minor Minor version number
	Minor int `json:"minor"`

	// Patch Patch version number
	Patch int `json:"patch"`
}

// SourceType Face detection source type
type SourceType string

// TagResponseDto defines model for TagResponseDto.
type TagResponseDto struct {
	// Color Tag color (hex)
	Color *string `json:"color,omitempty"`

	// CreatedAt Creation date
	CreatedAt time.Time `json:"createdAt"`

	// Id Tag ID
	Id string `json:"id"`

	// Name Tag name
	Name string `json:"name"`

	// ParentId Parent tag ID
	ParentId *string `json:"parentId,omitempty"`

	// UpdatedAt Last update date
	UpdatedAt time.Time `json:"updatedAt"`

	// Value Tag value (full path)
	Value string `json:"value"`
}

// UserAvatarColor User avatar color
type UserAvatarColor string

// UserResponseDto defines model for UserResponseDto.
type UserResponseDto struct {
	// AvatarColor User avatar color
	AvatarColor UserAvatarColor `json:"avatarColor"`

	// Email User email
	Email openapi_types.Email `json:"email"`

	// Id User ID
	Id openapi_types.UUID `json:"id"`

	// Name User name
	Name string `json:"name"`

	// ProfileChangedAt Profile change date
	ProfileChangedAt time.Time `json:"profileChangedAt"`

	// ProfileImagePath Profile image path
	ProfileImagePath string `json:"profileImagePath"`
}

// apiKeyContextKey is the context key for api_key security scheme
type apiKeyContextKey string

// bearerContextKey is the context key for bearer security scheme
type bearerContextKey string

// cookieContextKey is the context key for cookie security scheme
type cookieContextKey string

// UploadAssetParams defines parameters for UploadAsset.
type UploadAssetParams struct {
	Key  *string `form:"key,omitempty" json:"key,omitempty"`
	Slug *string `form:"slug,omitempty" json:"slug,omitempty"`

	// XImmichChecksum sha1 checksum that can be used for duplicate detection before the file is uploaded
	XImmichChecksum *string `json:"x-immich-checksum,omitempty"`
}

// GetAssetInfoParams defines parameters for GetAssetInfo.
type GetAssetInfoParams struct {
	Key  *string `form:"key,omitempty" json:"key,omitempty"`
	Slug *string `form:"slug,omitempty" json:"slug,omitempty"`
}

// UploadAssetMultipartRequestBody defines body for UploadAsset for multipart/form-data ContentType.
type UploadAssetMultipartRequestBody = AssetMediaCreateDto

// CheckBulkUploadJSONRequestBody defines body for CheckBulkUpload for application/json ContentType.
type CheckBulkUploadJSONRequestBody = AssetBulkUploadCheckDto

// AsPluginJsonSchemaPropertyAdditionalProperties0 returns the union data inside the PluginJsonSchemaProperty_AdditionalProperties as a PluginJsonSchemaPropertyAdditionalProperties0
func (t PluginJsonSchemaProperty_AdditionalProperties) AsPluginJsonSchemaPropertyAdditionalProperties0() (PluginJsonSchemaPropertyAdditionalProperties0, error) {
	var body PluginJsonSchemaPropertyAdditionalProperties0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPluginJsonSchemaPropertyAdditionalProperties0 overwrites any union data inside the PluginJsonSchemaProperty_AdditionalProperties as the provided PluginJsonSchemaPropertyAdditionalProperties0
func (t *PluginJsonSchemaProperty_AdditionalProperties) FromPluginJsonSchemaPropertyAdditionalProperties0(v PluginJsonSchemaPropertyAdditionalProperties0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePluginJsonSchemaPropertyAdditionalProperties0 performs a merge with any union data inside the PluginJsonSchemaProperty_AdditionalProperties, using the provided PluginJsonSchemaPropertyAdditionalProperties0
func (t *PluginJsonSchemaProperty_AdditionalProperties) MergePluginJsonSchemaPropertyAdditionalProperties0(v PluginJsonSchemaPropertyAdditionalProperties0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPluginJsonSchemaProperty returns the union data inside the PluginJsonSchemaProperty_AdditionalProperties as a PluginJsonSchemaProperty
func (t PluginJsonSchemaProperty_AdditionalProperties) AsPluginJsonSchemaProperty() (PluginJsonSchemaProperty, error) {
	var body PluginJsonSchemaProperty
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPluginJsonSchemaProperty overwrites any union data inside the PluginJsonSchemaProperty_AdditionalProperties as the provided PluginJsonSchemaProperty
func (t *PluginJsonSchemaProperty_AdditionalProperties) FromPluginJsonSchemaProperty(v PluginJsonSchemaProperty) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePluginJsonSchemaProperty performs a merge with any union data inside the PluginJsonSchemaProperty_AdditionalProperties, using the provided PluginJsonSchemaProperty
func (t *PluginJsonSchemaProperty_AdditionalProperties) MergePluginJsonSchemaProperty(v PluginJsonSchemaProperty) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PluginJsonSchemaProperty_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PluginJsonSchemaProperty_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// UploadAssetWithBody request with any body
	UploadAssetWithBody(ctx context.Context, params *UploadAssetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckBulkUploadWithBody request with any body
	CheckBulkUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CheckBulkUpload(ctx context.Context, body CheckBulkUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAssetInfo request
	GetAssetInfo(ctx context.Context, id openapi_types.UUID, params *GetAssetInfoParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PingServer request
	PingServer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServerVersion request
	GetServerVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) UploadAssetWithBody(ctx context.Context, params *UploadAssetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUploadAssetRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckBulkUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckBulkUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckBulkUpload(ctx context.Context, body CheckBulkUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckBulkUploadRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAssetInfo(ctx context.Context, id openapi_types.UUID, params *GetAssetInfoParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAssetInfoRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PingServer(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPingServerRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServerVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUploadAssetRequestWithBody generates requests for UploadAsset with any type of body
func NewUploadAssetRequestWithBody(server string, params *UploadAssetParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Key != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", *params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "slug", *params.Slug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XImmichChecksum != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-immich-checksum", *params.XImmichChecksum, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-immich-checksum", headerParam0)
		}

	}

	return req, nil
}

// NewCheckBulkUploadRequest calls the generic CheckBulkUpload builder with application/json body
func NewCheckBulkUploadRequest(server string, body CheckBulkUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCheckBulkUploadRequestWithBody(server, "application/json", bodyReader)
}

// NewCheckBulkUploadRequestWithBody generates requests for CheckBulkUpload with any type of body
func NewCheckBulkUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets/bulk-upload-check")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAssetInfoRequest generates requests for GetAssetInfo
func NewGetAssetInfoRequest(server string, id openapi_types.UUID, params *GetAssetInfoParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Key != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "key", *params.Key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Slug != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "slug", *params.Slug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPingServerRequest generates requests for PingServer
func NewPingServerRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/server/ping")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServerVersionRequest generates requests for GetServerVersion
func NewGetServerVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/server/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// UploadAssetWithBodyWithResponse request with any body
	UploadAssetWithBodyWithResponse(ctx context.Context, params *UploadAssetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadAssetResponse, error)

	// CheckBulkUploadWithBodyWithResponse request with any body
	CheckBulkUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckBulkUploadResponse, error)

	CheckBulkUploadWithResponse(ctx context.Context, body CheckBulkUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckBulkUploadResponse, error)

	// GetAssetInfoWithResponse request
	GetAssetInfoWithResponse(ctx context.Context, id openapi_types.UUID, params *GetAssetInfoParams, reqEditors ...RequestEditorFn) (*GetAssetInfoResponse, error)

	// PingServerWithResponse request
	PingServerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PingServerResponse, error)

	// GetServerVersionWithResponse request
	GetServerVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerVersionResponse, error)
}

type UploadAssetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AssetMediaResponseDto
	JSON201      *AssetMediaResponseDto
}

// Status returns HTTPResponse.Status
func (r UploadAssetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UploadAssetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UploadAssetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CheckBulkUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AssetBulkUploadCheckResponseDto
}

// Status returns HTTPResponse.Status
func (r CheckBulkUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckBulkUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CheckBulkUploadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAssetInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AssetResponseDto
}

// Status returns HTTPResponse.Status
func (r GetAssetInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAssetInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAssetInfoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PingServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServerPingResponse
}

// Status returns HTTPResponse.Status
func (r PingServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PingServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PingServerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServerVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServerVersionResponseDto
}

// Status returns HTTPResponse.Status
func (r GetServerVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServerVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// UploadAssetWithBodyWithResponse request with arbitrary body returning *UploadAssetResponse
func (c *ClientWithResponses) UploadAssetWithBodyWithResponse(ctx context.Context, params *UploadAssetParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UploadAssetResponse, error) {
	rsp, err := c.UploadAssetWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUploadAssetResponse(rsp)
}

// CheckBulkUploadWithBodyWithResponse request with arbitrary body returning *CheckBulkUploadResponse
func (c *ClientWithResponses) CheckBulkUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckBulkUploadResponse, error) {
	rsp, err := c.CheckBulkUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckBulkUploadResponse(rsp)
}

func (c *ClientWithResponses) CheckBulkUploadWithResponse(ctx context.Context, body CheckBulkUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckBulkUploadResponse, error) {
	rsp, err := c.CheckBulkUpload(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckBulkUploadResponse(rsp)
}

// GetAssetInfoWithResponse request returning *GetAssetInfoResponse
func (c *ClientWithResponses) GetAssetInfoWithResponse(ctx context.Context, id openapi_types.UUID, params *GetAssetInfoParams, reqEditors ...RequestEditorFn) (*GetAssetInfoResponse, error) {
	rsp, err := c.GetAssetInfo(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAssetInfoResponse(rsp)
}

// PingServerWithResponse request returning *PingServerResponse
func (c *ClientWithResponses) PingServerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PingServerResponse, error) {
	rsp, err := c.PingServer(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePingServerResponse(rsp)
}

// GetServerVersionWithResponse request returning *GetServerVersionResponse
func (c *ClientWithResponses) GetServerVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerVersionResponse, error) {
	rsp, err := c.GetServerVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerVersionResponse(rsp)
}

// ParseUploadAssetResponse parses an HTTP response from a UploadAssetWithResponse call
func ParseUploadAssetResponse(rsp *http.Response) (*UploadAssetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UploadAssetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AssetMediaResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AssetMediaResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseCheckBulkUploadResponse parses an HTTP response from a CheckBulkUploadWithResponse call
func ParseCheckBulkUploadResponse(rsp *http.Response) (*CheckBulkUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckBulkUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AssetBulkUploadCheckResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAssetInfoResponse parses an HTTP response from a GetAssetInfoWithResponse call
func ParseGetAssetInfoResponse(rsp *http.Response) (*GetAssetInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAssetInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AssetResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePingServerResponse parses an HTTP response from a PingServerWithResponse call
func ParsePingServerResponse(rsp *http.Response) (*PingServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PingServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServerPingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetServerVersionResponse parses an HTTP response from a GetServerVersionWithResponse call
func ParseGetServerVersionResponse(rsp *http.Response) (*GetServerVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServerVersionResponseDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
